FROM ghcr.io/tna76874/schoolnotebookbase:stable-2023110208

USER root

ENV SETUP_STATUS="production"
ENV REPO_USER="tna76874"
ENV REPO_NAME="notebooks-school-java"

## ENSURE ENTRYPOINTS WITH SCRIPTS
COPY ./scripts/docker-entrypoint.sh /
COPY ./scripts/run_on_init /usr/local/bin/
RUN chmod 775 /usr/local/bin/run_on_init

ARG NB_USER=jovyan
ARG NB_UID=1000
ENV USER ${NB_USER}
ENV NB_UID ${NB_UID}
ENV HOME /home/${NB_USER}

RUN chmod 775 /docker-entrypoint.sh

# INSTALL JAVA
COPY ./java /java
RUN mkdir /work
RUN chown -R ${NB_USER} /java && chown -R ${NB_USER} /work && chmod 775 -R /java

RUN cd /java && python install.py

RUN apt-get update -y && \
    apt-get install -y openjdk-18-jdk

USER ${NB_USER}

RUN rm -rf /home/${NB_USER}/work 

ENTRYPOINT ["/docker-entrypoint.sh"]