name: Docker Image CI

on:
  push:
    branches:
      - master
      - stable
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
          COMMIT_HASH=$(git rev-parse --short HEAD)

          # Build image for master branch
          if [ ${{ github.ref }} == 'refs/heads/master' ]; then
            CHANNEL="latest"
          fi

          # Build image for stable branch
          if [ ${{ github.ref }} == 'refs/heads/stable' ]; then
            CHANNEL="stable"
          fi

          docker build . --file Dockerfile --tag schoolnotebookjava:${COMMIT_HASH}
          docker build . --file Dockerfile --tag schoolnotebookjava:${CHANNEL}